'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Namespace MVC.PredefinedReports

	Partial Public Class TestReport
		Inherits DevExpress.XtraReports.UI.XtraReport

		Private Sub InitializeComponent()
			Dim reportInitializer As New DevExpress.XtraReports.ReportInitializer(Me, "MVC.PredefinedReports.TestReport.repx")

			' Controls
			Me.TopMargin = reportInitializer.GetControl(Of DevExpress.XtraReports.UI.TopMarginBand)("TopMargin")
			Me.ReportHeader = reportInitializer.GetControl(Of DevExpress.XtraReports.UI.ReportHeaderBand)("ReportHeader")
			Me.GroupHeader1 = reportInitializer.GetControl(Of DevExpress.XtraReports.UI.GroupHeaderBand)("GroupHeader1")
			Me.Detail = reportInitializer.GetControl(Of DevExpress.XtraReports.UI.DetailBand)("Detail")
			Me.BottomMargin = reportInitializer.GetControl(Of DevExpress.XtraReports.UI.BottomMarginBand)("BottomMargin")
			Me.label1 = reportInitializer.GetControl(Of DevExpress.XtraReports.UI.XRLabel)("label1")
			Me.table1 = reportInitializer.GetControl(Of DevExpress.XtraReports.UI.XRTable)("table1")
			Me.tableRow1 = reportInitializer.GetControl(Of DevExpress.XtraReports.UI.XRTableRow)("tableRow1")
			Me.tableCell1 = reportInitializer.GetControl(Of DevExpress.XtraReports.UI.XRTableCell)("tableCell1")
			Me.tableCell2 = reportInitializer.GetControl(Of DevExpress.XtraReports.UI.XRTableCell)("tableCell2")
			Me.tableCell3 = reportInitializer.GetControl(Of DevExpress.XtraReports.UI.XRTableCell)("tableCell3")
			Me.table2 = reportInitializer.GetControl(Of DevExpress.XtraReports.UI.XRTable)("table2")
			Me.tableRow2 = reportInitializer.GetControl(Of DevExpress.XtraReports.UI.XRTableRow)("tableRow2")
			Me.tableCell4 = reportInitializer.GetControl(Of DevExpress.XtraReports.UI.XRTableCell)("tableCell4")
			Me.tableCell5 = reportInitializer.GetControl(Of DevExpress.XtraReports.UI.XRTableCell)("tableCell5")
			Me.tableCell6 = reportInitializer.GetControl(Of DevExpress.XtraReports.UI.XRTableCell)("tableCell6")
			Me.pictureBox1 = reportInitializer.GetControl(Of DevExpress.XtraReports.UI.XRPictureBox)("pictureBox1")
			Me.pageInfo1 = reportInitializer.GetControl(Of DevExpress.XtraReports.UI.XRPageInfo)("pageInfo1")
			Me.pageInfo2 = reportInitializer.GetControl(Of DevExpress.XtraReports.UI.XRPageInfo)("pageInfo2")

			' Data Sources
			Me.sqlDataSource1 = reportInitializer.GetDataSource(Of DevExpress.DataAccess.Sql.SqlDataSource)("sqlDataSource1")

			' Styles
			Me.Title = reportInitializer.GetStyle("Title")
			Me.DetailCaption1 = reportInitializer.GetStyle("DetailCaption1")
			Me.DetailData1 = reportInitializer.GetStyle("DetailData1")
			Me.DetailData3_Odd = reportInitializer.GetStyle("DetailData3_Odd")
			Me.PageInfo = reportInitializer.GetStyle("PageInfo")
		End Sub
		Private TopMargin As DevExpress.XtraReports.UI.TopMarginBand
		Private ReportHeader As DevExpress.XtraReports.UI.ReportHeaderBand
		Private GroupHeader1 As DevExpress.XtraReports.UI.GroupHeaderBand
		Private Detail As DevExpress.XtraReports.UI.DetailBand
		Private BottomMargin As DevExpress.XtraReports.UI.BottomMarginBand
		Private label1 As DevExpress.XtraReports.UI.XRLabel
		Private table1 As DevExpress.XtraReports.UI.XRTable
		Private tableRow1 As DevExpress.XtraReports.UI.XRTableRow
		Private tableCell1 As DevExpress.XtraReports.UI.XRTableCell
		Private tableCell2 As DevExpress.XtraReports.UI.XRTableCell
		Private tableCell3 As DevExpress.XtraReports.UI.XRTableCell
		Private table2 As DevExpress.XtraReports.UI.XRTable
		Private tableRow2 As DevExpress.XtraReports.UI.XRTableRow
		Private tableCell4 As DevExpress.XtraReports.UI.XRTableCell
		Private tableCell5 As DevExpress.XtraReports.UI.XRTableCell
		Private tableCell6 As DevExpress.XtraReports.UI.XRTableCell
		Private pictureBox1 As DevExpress.XtraReports.UI.XRPictureBox
		Private pageInfo1 As DevExpress.XtraReports.UI.XRPageInfo
		Private pageInfo2 As DevExpress.XtraReports.UI.XRPageInfo
		Private sqlDataSource1 As DevExpress.DataAccess.Sql.SqlDataSource
		Private Title As DevExpress.XtraReports.UI.XRControlStyle
		Private DetailCaption1 As DevExpress.XtraReports.UI.XRControlStyle
		Private DetailData1 As DevExpress.XtraReports.UI.XRControlStyle
		Private DetailData3_Odd As DevExpress.XtraReports.UI.XRControlStyle
		Private PageInfo As DevExpress.XtraReports.UI.XRControlStyle
	End Class
End Namespace